package it.polimi.ingsw.view;

public enum ViewEvent {
    CONNECTION_INFO, GAMEMODE, NICKNAME, NUMBER_OF_PLAYERS, KEEP_LEADERS,
    ACTION, LEADER_ACTION, DEVCARD, DEVCARD_POSITION, MARBLES, CONVERT_WHITE,
    WAREHOUSE_CONFIG, PRODUCTION, CHOOSE_RESOURCES, FREE_REQUIREMENT, CHOOSE_PRODUCT
}
